apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    app: jenkins
spec:
  containers:
    - image: abhidevops24/devops20:jenkin-20
      name: jenkins-pod
      ports:
      - containerPort: 8080

