apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-sts
spec:
  serviceName: mariadb-service # Must match the name of the service
  replicas: 1                   # Number of replicas
  selector:
    matchLabels:
      app: mariadb-sts          # Selector for the pods
  template:
    metadata:
      labels:
        app: mariadb-sts        # Labels for the pods
    spec:
      containers:
        - name: mriadb
          image: abhidevops24/devops20:mariadb-20 #private Docker
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password                   # root password for MariaDB
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
     imagePullSecrets:
       - name: regcred           # Secret to pull from the private repository
     volumes:
       - name: mariadb-data
         emptyDir: {}        # Replace this with a persistent volume if needed

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  ports:
    - port: 3306        # The port that the service will expose
      targetPort: 3306  # The port on the container
  clusterIP: None       # This creates a headless service
  selector:
    app: mariadb-sts    # Selector to match the pods
