---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath: # use this for testing on a local cluster(like mriadb)
    path: /mnt/data/mariadb

