apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  # namespace: my-namespace
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:      
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "200Mi"
            cpu: "100m"
